version: '3.7'
services:

  gate-simulator:
    build: gate-simulator/
    image: gate-simulator:1.0
    ports:
      - '9999:9999'

  mysql:
    image: mysql:8.0
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db_shop
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=asdvbn123

  app-shop:
    build: artifacts/
    image: aqa-shop:latest
    depends_on:
      - mysql
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/db_shop
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=asdvbn123
      - SPRING_JPA_DATABASE=POSTGRESQL