version: '3.7'
services:

  gate-simulator:
    build: gate-simulator/
    image: gate-simulator:1.0
    ports:
      - '9999:9999'

  postgresql:
    container_name: postgresql
    image: postgres:12-alpine
    ports:
      - '5436:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_shop
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=asdvbn123
  app-shop:
    build: artifacts/
    image: aqa-shop:latest
    depends_on:
      - postgresql
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/db_shop
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=asdvbn123
      - SPRING_JPA_DATABASE=POSTGRESQL
      - SPRING_CREDIT_GATE_URL=http://gate-simulator:9999/credit
      - SPRING_PAYMENT_GATE_URL=http://gate-simulator:9999/payment